### ISSUE TITLE
Hearth and Home

### ISSUE THREAD

**Issue by sdfg2** [MaterousApps/Valheim-Auto-Map-Pins-Configurable#4]
Hello,

I know you're not actively modding for Valheim right now, but is there any chance of an update for this for H&H?  It's one of the few things I miss the most, especially the custom icons which make things much easier to see.

**Comment by MaterousApps** [comment]
I'll see what my work schedule is like this upcoming week and see if I can
fiddle around with this to get it working with H&H.

**Comment by Squeech007** [comment]
[AutoMapPins](https://github.com/bdew-valheim/AutoMapPins) released an updated [dll ](https://www.dropbox.com/s/c7km1vi8es7bcol/AutoMapPins.dll?dl=0)but no source unfortunatly, i assume that might have helped :(

**Comment by sdfg2** [comment]
> [AutoMapPins](https://github.com/bdew-valheim/AutoMapPins) released an updated [dll ](https://www.dropbox.com/s/c7km1vi8es7bcol/AutoMapPins.dll?dl=0)but no source unfortunatly, i assume that might have helped :(

If that's the one linked in the comments, that was just a recompilation of the existing source files, nothing changed as far as I know.  It works, but it has no where near the scope of this one (berries, mushrooms etc, what to save or just show, custom icons).

**Comment by Squeech007** [comment]
Sadly i just didnt (still dont actually) know what "recompiling" means.. but yes, its a way simpler mod than yours.. (thats also a reason why i like yours more XD). 
Anyway even if you ain't got the time doing the magic on your mod to update it, i want to thank you alot for the great mod! it really made the game so much better. I mean i used to do those markings by hand.. soooo annoying!
Thx!!!

**Comment by MaterousApps** [comment]
It looks like the code that the developers put in to allow the default pins to be filterable (right clicking to turn on/off) put in an array that was limited to just the pinTypes that are the default ones.  Since I was using custom pinTypes, I had to override the array to allow for all of my options as well!

**Comment by dougthedogboy** [comment]
I see it has been updated on Nexus, will it be updated on Thunderstore?

edit... It just updated. Thanks so much for your mod

**Comment by MaterousApps** [comment]
It should be updated now.
